# Generated by Django 4.1.4 on 2022-12-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_solid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='solid',
        ),
    ]
